[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = []
dependencies = ["rich==13.8.1"]
description = ''
name = "painlezz_formatterz"
readme = "README.md"
requires-python = ">=3.12,<3.13"
version = "0.0.1"
