[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = []
dependencies = []
description = ''
name = "painlezz_formatterz"
readme = "README.md"
requires-python = ">=3.13,<3.14"
version = "0.0.1"
