version: "3.9"

services:
  postgres:
    container_name: postgres
    build:
      context: docker/postgres/
    image: pysilo/postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-core-data:/bitnami/redis/data
volumes:
  postgres_data:
    driver: local
  redis-core-data:
    driver: local
