[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = []
dependencies = ["structlog==24.4.0"]
description = ''
name = "painlezz_async"
readme = "README.md"
requires-python = ">=3.12,<3.13"
version = "0.0.1"
