[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = []
dependencies = ["libcst==1.4.0", "toml==0.10.2"]
description = ''
name = "painlezz_projectz"
readme = "README.md"
requires-python = ">=3.12,<3.13"
version = "0.0.1"
