"""init

Revision ID: 05fe7fd5b25f
Revises:
Create Date: 2025-06-27 17:15:56.421858

"""

from typing import Sequence

import sqlalchemy as sa
import ezpz_registry.db.types.http_url
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05fe7fd5b25f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "api_keys",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("key_hash", sa.String(length=64), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("permissions", postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column("active", sa.Boolean(), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("id"),
  )
  op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
  op.create_table(
    "plugins",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("package_name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.Text(), nullable=False),
    sa.Column("aliases", postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column("version", sa.String(length=50), nullable=True),
    sa.Column("author", sa.String(length=100), nullable=True),
    sa.Column("homepage", ezpz_registry.db.types.http_url.HttpUrlType(length=500), nullable=True),
    sa.Column("verified", sa.Boolean(), nullable=False),
    sa.Column("submitted_by", sa.String(length=100), nullable=True),
    sa.Column("verification_token", sa.String(length=32), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("id"),
  )
  op.create_index(op.f("ix_plugins_name"), "plugins", ["name"], unique=True)
  op.create_index(op.f("ix_plugins_package_name"), "plugins", ["package_name"], unique=True)
  op.create_index(op.f("ix_plugins_verified"), "plugins", ["verified"], unique=False)
  op.create_table(
    "plugin_downloads",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("plugin_id", sa.Uuid(), nullable=False),
    sa.Column("date", sa.DateTime(timezone=True), nullable=False),
    sa.Column("downloads", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
      ["plugin_id"],
      ["plugins.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("id"),
    sa.UniqueConstraint("plugin_id", "date", name="unique_plugin_date"),
  )
  op.create_index(op.f("ix_plugin_downloads_date"), "plugin_downloads", ["date"], unique=False)
  op.create_index(op.f("ix_plugin_downloads_plugin_id"), "plugin_downloads", ["plugin_id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_plugin_downloads_plugin_id"), table_name="plugin_downloads")
  op.drop_index(op.f("ix_plugin_downloads_date"), table_name="plugin_downloads")
  op.drop_table("plugin_downloads")
  op.drop_index(op.f("ix_plugins_verified"), table_name="plugins")
  op.drop_index(op.f("ix_plugins_package_name"), table_name="plugins")
  op.drop_index(op.f("ix_plugins_name"), table_name="plugins")
  op.drop_table("plugins")
  op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
  op.drop_table("api_keys")
  # ### end Alembic commands ###
