"""rev1

Revision ID: bccb119c66f7
Revises: 0d38490e7c77
Create Date: 2025-07-02 11:30:41.703884

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bccb119c66f7"
down_revision: str | None = "0d38490e7c77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_unique_constraint(None, "plugin_downloads", ["id"])
  op.create_unique_constraint(None, "plugins", ["id"])
  op.drop_column("plugins", "submitted_by")
  op.drop_column("plugins", "verification_token")
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("plugins", sa.Column("verification_token", sa.VARCHAR(length=32), autoincrement=False, nullable=True))
  op.add_column("plugins", sa.Column("submitted_by", sa.VARCHAR(length=100), autoincrement=False, nullable=True))
  op.drop_constraint(None, "plugins", type_="unique")
  op.drop_constraint(None, "plugin_downloads", type_="unique")
  # ### end Alembic commands ###
